version: 2

formats:
  - htmlzip

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"

conda:
  environment: docs/environment-docs.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: True

python:
  install:
    - method: pip
      path: .
