name: msibi-readthedocs
channels:
  - conda-forge
dependencies:
  - sphinx==7.2.4
  - sphinx_rtd_theme==1.3.0
  - freud
  - gsd >= 3.0
  - hoomd >= 4.0
  - python >= 3.9
  - pandas
  - cmeutils >= 1.2
  - more-itertools
