name: msibi
channels:
- conda-forge
dependencies:
- freud >=3.0,<3.2
- gsd >=3.0
- hoomd >=5.0
- matplotlob
- networkx
- boltons
- python >=3.10
- pandas
- numpy >=2.0,<2.3
- more-itertools
- pip:
    - git+https://github.com/cmelab/cmeutils.git@main
