name: msibi3
channels:
- conda-forge
dependencies:
- freud
- gsd
- more-itertools
- numpy
- pip
- py3Dmol
- python
- pytest
- pytest-cov
- jupyter
- ipython
- nodejs>=10
- pip:
    - git+https://github.com/cmelab/cmeutils
