name: msibi-dev
channels:
- conda-forge
dependencies:
- freud >=3.0,<3.2
- gsd >=3.0
- hoomd >=4.0,<5.0
- python >=3.10
- pandas
- cmeutils >=1.3
- numpy <2.0
- more-itertools
- pytest
- pytest-cov
- pre-commit
