name: msibi
channels:
- conda-forge
dependencies:
- freud >=3.4
- cmeutils >=1.4
- gsd >=3.0
- hoomd >=5.0
- matplotlob
- python >=3.10,<=3.13
- pandas
- mdanalysis <3.0
- numpy >=2.0,<2.3
- more-itertools
- pip:
    - build
