name: msibi
channels:
- conda-forge
dependencies:
- freud=2.7.0
- gsd=2.4.1
- hoomd=2.9.6=gpu_py39he2a7f1f_1
- mbuild=0.13.1
- more-itertools
- numpy=1.20.1
- pip=21.0
- py3Dmol=0.8.0
- python=3.9
- pytest
- pytest-cov
- jupyterlab
- ipython
- nodejs>=10
- pip:
    - git+https://github.com/cmelab/cmeutils
