name: msibi-docs
channels:
  - conda-forge
dependencies:
  - mdanalysis=2.9
  - sphinx==8.1
  - sphinx_rtd_theme>=3.0
  - freud >=3.0
  - gsd >=3.0
  - hoomd >=5.0,<5.4
  - python >=3.10
  - pandas
  - numpy >=2.0
  - cmeutils >=1.4
  - nbsphinx
  - more-itertools
  - pygments>=2.12.0
  - nbconvert>=6.0.0
  - IPython>=7.0.0
