name: pytest

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/pytest.yml'
      - 'msibi/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'msibi/**'
      - '.github/workflows/pytest.yml'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: 
        image: mambaorg/micromamba:0.15.2

    steps:
    - uses: actions/checkout@v2

    - name: Build environment
      run: micromamba install -y -n base -f environment.yml
 
    - name: Run pytest with coverage report
      run: python -m pytest --cov=./ --cov-report=xml -v
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
