name: pytest

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/pytest.yml'
      - 'environment-dev.yml'
      - 'msibi/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'msibi/**'
      - 'environment-dev.yml'
      - '.github/workflows/pytest.yml'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment-dev.yml
        miniforge-variant: Mambaforge
        miniforge-version: 23.11.0-0 
        use-mamba: true
    
    - name: Install package
      shell: bash -l {0}
      run: pip install .
 
    - name: Run pytest with coverage report
      shell: bash -l {0}
      run: python -m pytest -rs -v --cov=./ --cov-report=xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
